// Predefined achievements configuration
export const ACHIEVEMENTS_CONFIG = {
  // Streak Achievements
  'first-streak': {
    id: 'first-streak',
    title: 'First Steps',
    description: 'Complete your first habit for 3 days in a row',
    icon: '🥉',
    category: 'streaks',
    points: 10,
    condition: (data) => data.maxStreak >= 3,
  },
  'week-warrior': {
    id: 'week-warrior',
    title: 'Week Warrior',
    description: 'Maintain a 7-day streak on any habit',
    icon: '📅',
    category: 'streaks',
    points: 25,
    condition: (data) => data.maxStreak >= 7,
  },
  'streak-master': {
    id: 'streak-master',
    title: 'Streak Master',
    description: 'Achieve a 30-day streak on any habit',
    icon: '🔥',
    category: 'streaks',
    points: 100,
    condition: (data) => data.maxStreak >= 30,
  },
  'unstoppable': {
    id: 'unstoppable',
    title: 'Unstoppable Force',
    description: 'Reach a 100-day streak',
    icon: '⚡',
    category: 'streaks',
    points: 500,
    condition: (data) => data.maxStreak >= 100,
  },

  // Completion Achievements
  'habit-creator': {
    id: 'habit-creator',
    title: 'Habit Creator',
    description: 'Create your first habit',
    icon: '✨',
    category: 'milestones',
    points: 5,
    condition: (data) => data.totalHabits >= 1,
  },
  'multi-tasker': {
    id: 'multi-tasker',
    title: 'Multi-Tasker',
    description: 'Create 5 different habits',
    icon: '🎯',
    category: 'milestones',
    points: 20,
    condition: (data) => data.totalHabits >= 5,
  },
  'perfectionist': {
    id: 'perfectionist',
    title: 'Perfectionist',
    description: 'Achieve 100% completion rate in a week',
    icon: '💯',
    category: 'completion',
    points: 50,
    condition: (data) => data.weeklyCompletionRate >= 100,
  },
  'consistency-king': {
    id: 'consistency-king',
    title: 'Consistency King',
    description: 'Complete habits for 30 days straight (any combination)',
    icon: '👑',
    category: 'consistency',
    points: 75,
    condition: (data) => data.totalCompletedDays >= 30,
  },

  // Special Achievements
  'early-bird': {
    id: 'early-bird',
    title: 'Early Bird',
    description: 'Complete habits before 8 AM for 7 days',
    icon: '🌅',
    category: 'special',
    points: 30,
    condition: (data) => data.earlyBirdCount >= 7,
  },
  'night-owl': {
    id: 'night-owl',
    title: 'Night Owl',
    description: 'Complete habits after 10 PM for 7 days',
    icon: '🦉',
    category: 'special',
    points: 30,
    condition: (data) => data.nightOwlCount >= 7,
  },
  'comeback-kid': {
    id: 'comeback-kid',
    title: 'Comeback Kid',
    description: 'Start a new streak after breaking one',
    icon: '🔄',
    category: 'special',
    points: 15,
    condition: (data) => data.comebackStreaks >= 1,
  },
};

export const ACHIEVEMENT_CATEGORIES = {
  streaks: { name: 'Streaks', icon: '🔥', color: 'orange' },
  completion: { name: 'Completion', icon: '✅', color: 'green' },
  consistency: { name: 'Consistency', icon: '📈', color: 'blue' },
  milestones: { name: 'Milestones', icon: '🏆', color: 'purple' },
  special: { name: 'Special', icon: '⭐', color: 'pink' },
};